# Generated by Django 6.0.4 on 2026-05-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('direction', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Academico')),
                ('biografia', models.TextField(max_length=1000, verbose_name='Biografia')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo Electronico')),
                ('dedicacion', models.CharField(max_length=100, verbose_name='Dedicación Personal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['-created'],
            },
        ),
    ]
