# Generated by Django 6.0.5 on 2026-05-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='correo_electronico',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='dedicacion_personal',
            new_name='dedicacion',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='titulo_academico',
            new_name='titulo',
        ),
    ]
