# Generated by Django 6.0.5 on 2026-05-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='img',
            new_name='imagen',
        ),
    ]
