# Generated by Django 6.0.5 on 2026-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_img_proyectos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
